import type { Metadata } from "next";
import { IBM_Plex_Sans_KR, JetBrains_Mono, Noto_Sans_KR } from "next/font/google";
import "./globals.css";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const notoSansKr = Noto_Sans_KR({
  variable: "--font-noto-sans-kr",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const ibmPlexSansKr = IBM_Plex_Sans_KR({
  variable: "--font-ibm-plex-sans-kr",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.className} ${jetbrainsMono.variable} ${notoSansKr.variable} ${ibmPlexSansKr.variable} antialiased`}
        style={{ fontFamily: 'var(--font-jetbrains-mono), "JetBrains Mono", monospace' }}
      >
        {children}
      </body>
    </html>
  );
}
